version: "3"
services: 
  app:
    restart: always
    build: .
    container_name: node_test
    image: node_test
    environment:
      - "PORT=3800"
    ports:
      - "3800:3800"
    networks:
      - mongo  
  mongo:
    restart: always
    container_name: mongo
    image: mongo
    networks:
      - mongo

networks:
  mongo:
# Defult docker compos create a network between services